TRANSCRIPTION_JOB_INITIALIZED = "TRANSCRIPTION_JOB_INITIALIZED"
TRANSCRIPTION_JOB_COMPLETED = "TRANSCRIPTION_JOB_COMPLETED"
TRANSCRIPTION_JOB_FAILED = "TRANSCRIPTION_JOB_FAILED"

TRANSCRIPT_GENERATION_IN_PROGRESS = "TRANSCRIPT_GENERATION_IN_PROGRESS"
TRANSCRIPT_GENERATION_COMPLETED = "TRANSCRIPT_GENERATION_COMPLETED"

DIARIZATION_IN_PROGRESS = "DIARIZATION_IN_PROGRESS"
DIARIZATION_COMPLETED = "DIARIZATION_COMPLETED"

TRANSCRIPTION_JOB_OUTPUT_EXPORT_COMPLETED = "TRANSCRIPTION_JOB_OUTPUT_EXPORT_COMPLETED"

