TRANSCRIPTION_INITIALIZING = "TRANSCRIPTION_INITIALIZING"
TRANSCRIPTION_IN_PROGRESS = "TRANSCRIPTION_IN_PROGRESS"
TRANSCRIPTION_COMPLETED = "TRANSCRIPTION_COMPLETED"
TRANSCRIPTION_FAILED = "TRANSCRIPTION_FAILED"

DIARIZATION_INITIALIZING = "DIARIZATION_INITIALIZING"
DIARIZATION_COMPLETED = "DIARIZATION_COMPLETED"
