export const TRANSCRIPTS_FETCH_STATUS = {
  REQUESTED: "REQUESTED",
  STARTED: "STARTED",
  COMPLETED: "COMPLETED",
  FAILED: "FAILED",
};

export const PAGE_SIZE = 6;

export const TRANSCRIPTION_VIEWER_MODE = {
  VIEWER: "Viewer",
  EDITOR: "Editor",
};
