# Generated by Django 4.2 on 2024-01-22 17:49

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="AudioMetadata",
            fields=[
                (
                    "audioId",
                    models.CharField(max_length=255, primary_key=True, serialize=False),
                ),
                ("audioFileLocation", models.FileField(upload_to="files/")),
                ("durationInSeconds", models.FloatField()),
                ("audioFormat", models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name="TranscriptionJobHistory",
            fields=[
                (
                    "transcriptionId",
                    models.CharField(max_length=255, primary_key=True, serialize=False),
                ),
                ("runMode", models.CharField(max_length=255)),
                ("status", models.CharField(max_length=255)),
                ("context", models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name="TranscriptMetadata",
            fields=[
                (
                    "transcriptionId",
                    models.CharField(max_length=255, primary_key=True, serialize=False),
                ),
                ("sourceLanguage", models.CharField(max_length=255)),
                ("createdTimestamp", models.TimeField()),
                ("updatedTimestamp", models.TimeField()),
                ("transcriptFileLocation", models.FileField(upload_to="files/")),
                ("audioMetadataKey", models.CharField(max_length=255)),
            ],
        ),
    ]
