# Generated by Django 4.2 on 2024-01-27 21:11

from django.db import migrations, models
import transcribe.models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="TranscriptMetadata",
            fields=[
                (
                    "transcriptionId",
                    models.CharField(max_length=255, primary_key=True, serialize=False),
                ),
                ("title", models.CharField(max_length=255)),
                ("sourceLanguage", models.CharField(max_length=255)),
                (
                    "speakerMap",
                    models.JSONField(
                        validators=[
                            transcribe.models.validate_json,
                            transcribe.models.validate_speaker_map,
                        ]
                    ),
                ),
                ("durationInSeconds", models.FloatField()),
                ("audioFormat", models.CharField(max_length=255)),
                ("createdTimestamp", models.TimeField()),
                ("updatedTimestamp", models.TimeField()),
                ("status", models.CharField(max_length=255)),
                ("runMode", models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name="Transcript",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("transcriptionId", models.CharField(max_length=255)),
                ("startTimeInSeconds", models.CharField(max_length=255)),
                (
                    "transcriptSegment",
                    models.JSONField(
                        validators=[
                            transcribe.models.validate_json,
                            transcribe.models.validate_transcript_segments,
                        ]
                    ),
                ),
            ],
            options={
                "unique_together": {("transcriptionId", "startTimeInSeconds")},
            },
        ),
    ]
