# Generated by Django 4.2 on 2024-01-27 21:21

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("transcribe", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="transcript",
            name="startTimeInSeconds",
            field=models.FloatField(),
        ),
    ]
