# Generated by Django 4.2 on 2024-01-25 18:23

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("transcribe", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="transcriptionjobhistory",
            name="endDate",
            field=models.CharField(default="null", max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="transcriptionjobhistory",
            name="startDate",
            field=models.CharField(default="null", max_length=255),
            preserve_default=False,
        ),
    ]
